# Dependencies
markdown:     kramdown
highlighter:  rouge
exclude:      [vendor]

# Permalinks
permalink:    pretty

# Setup
title:        ./brooks.sh
description:  'The ramblings of Brooks'
url:          http://brooks.sh
baseurl:

author:
  name:       'Brooks Swinnerton'
  url:        https://twitter.com/bswinnerton

paginate:     10

kramdown:
  auto_ids: true
