# Dependencies
markdown:         kramdown
highlighter:      rouge
exclude:          [vendor]

# Permalinks
permalink:        pretty

# Setup
title:            Listenings
description:      'The ramblings of Brooks'
url:              http://listenin.gs
baseurl:          /

author:
  name:           'Brooks Swinnerton'
  url:            https://listenin.gs

paginate:         5
